# Generated by Django 4.0.4 on 2022-06-24 12:25

from django.db import migrations, models
import medetsin_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jamoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='jamoa _rasmlari', validators=[medetsin_app.utils.rasm_olchami])),
                ('ismi', models.CharField(max_length=100)),
                ('lavozimi', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=9)),
            ],
        ),
    ]
