# Generated by Django 4.0.4 on 2022-06-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medetsin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamoa',
            name='number',
        ),
    ]
